"""Check the published English pages: rendered math, navigation, links, anchors, fonts, figures.

Adapted from rjguo1208/Holstein-model scripts/check_site.py for an English-only site:
there is no translation catalog or language switch, and any CJK text is an error.
"""
from html.parser import HTMLParser
from pathlib import Path
import re
from urllib.parse import unquote, urlsplit
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
CJK = re.compile(r"[⺀-〿぀-ヿ㐀-䶿一-鿿가-힯豈-﫿＀-￯]")


class Page(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []
        self.ids = set()
        self.math_count = 0
        self.mathml_count = 0
        self.images = 0
        self.lang = None
        self.nav = None
        self.page_links = []
        self.cjk = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        assert tag not in {"script", "merror"}, f"Unexpected element: {tag}"
        classes = (attrs.get("class") or "").split()
        if tag == "html":
            self.lang = attrs.get("lang")
        if tag == "nav":
            self.nav = classes
        if tag == "a" and self.nav and "site-nav" in self.nav:
            self.page_links.append(attrs)
        for name in ("alt", "title", "aria-label", "content"):
            if CJK.search(attrs.get(name) or ""):
                self.cjk.append(attrs[name])
        assert "katex-error" not in classes, "Unrendered formula"
        self.math_count += "katex" in classes
        self.mathml_count += tag == "math"
        if tag == "img":
            assert attrs.get("alt"), "An image needs alternative text"
            self.images += 1
        if "id" in attrs:
            assert attrs["id"] not in self.ids, f"Duplicate id: {attrs['id']}"
            self.ids.add(attrs["id"])
        for name in ("src", "href"):
            if attrs.get(name):
                self.links.append(attrs[name])

    def handle_endtag(self, tag):
        if tag == "nav":
            self.nav = None

    def handle_data(self, data):
        if CJK.search(data):
            self.cjk.append(data.strip())


def check_link(path, link):
    url = urlsplit(link)
    if url.scheme or url.netloc:
        return
    target = (path.parent / unquote(url.path)).resolve() if url.path else path
    assert SITE in target.parents, f"Link escapes site: {link}"
    assert target.is_file(), f"Missing local resource: {link}"
    if url.fragment and target.suffix == ".html":
        parser = Page()
        parser.feed(target.read_text())
        assert unquote(url.fragment) in parser.ids, f"Missing anchor: {link}"


names = sorted(p.name for p in (ROOT / "src").glob("*.html"))
pages = {}
math_count = 0
for path in sorted(SITE.rglob("*.html")):
    relative = path.relative_to(SITE).as_posix()
    assert relative in names, f"Unexpected page without a source: {relative}"
    text = path.read_text()
    assert text.startswith(f"<!-- Generated from src/{path.name}."), f"Not generated by the build: {relative}"
    page = Page()
    page.feed(text)
    pages[relative] = page
    for link in page.links:
        check_link(path, link)
    source = (ROOT / "src" / path.name).read_text()
    expressions = re.findall(r"\\\[([\s\S]*?)\\\]|\\\(([\s\S]*?)\\\)", source)
    assert page.math_count == len(expressions) == page.mathml_count, f"Incomplete LaTeX/MathML rendering: {relative}"
    assert page.math_count > 0, f"No rendered math: {relative}"
    assert page.lang == "en", f"Page language must be en: {relative}"
    assert not page.cjk, f"Non-English text in {relative}: {page.cjk[:3]}"
    assert sorted(link["href"] for link in page.page_links) == names, f"Incomplete page navigation: {relative}"
    assert [link["href"] for link in page.page_links if link.get("aria-current") == "page"] == [path.name], \
        f"Current page not marked in navigation: {relative}"
    math_count += page.math_count
assert sorted(pages) == names, "Every source page must have a generated page"

for css in (SITE / "assets").rglob("*.css"):
    for link in re.findall(r"url\(['\"]?([^)'\"]+)['\"]?\)", css.read_text()):
        check_link(css, link)

plots = sorted((SITE / "results").glob("*.svg")) if (SITE / "results").is_dir() else []
for plot in plots:
    tree = ET.parse(plot)
    assert tree.getroot().get("viewBox"), f"Missing scalable bounds: {plot.name}"
    assert not tree.findall(".//{http://www.w3.org/2000/svg}image"), f"Raster image in {plot.name}"
    assert not tree.findall(".//{http://www.w3.org/2000/svg}script"), f"Script in {plot.name}"
    assert plot.with_suffix(".pdf").is_file(), f"Missing PDF: {plot.name}"

print(f"OK: {len(pages)} English pages; {math_count} LaTeX expressions with MathML; {len(plots)} scientific plots; "
      "page navigation, local links, anchors and fonts.")
